---
title: BOB
timezone: UTC
collections:
  affordances:
    title: Affordances
    output: true
    permalink: "/:collection/:title/"
  basics:
    title: Basics
    output: true
    permalink: "/:collection/:title/"
  color:
    title: Color
    output: true
    permalink: "/:collection/:title/"
  gestalt:
    title: Gestalt
    output: true
    permalink: "/:collection/:title/"
  iconography:
    title: Iconography
    output: true
    permalink: "/:collection/:title/"
  imagery:
    title: Imagery
    output: true
    permalink: "/:collection/:title/"
  layout:
    title: Layout
    output: true
    permalink: "/:collection/:title/"
  posts:
    title: Posts
    output: true
  typography:
    title: Typography
    output: true
    permalink: "/:collection/:title/"
  uploads:
    title: Uploads
    output: true
email: bob@bob.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://localhost:4000/
videourl: "/videos/exports/"
twitter_username: jekyllrb
github_username: jekyll
excerpt_separator: "<!--more-->"
permalink: "/:categories/:title.html"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
kramdown:
  input: GFM
  hard_wrap: false
